import type { PromptTemplate } from "@/lib/prompt/types";

const NOW = 1_710_000_000_000;

function createBuiltinTemplate(template: Omit<PromptTemplate, "builtin" | "version" | "createdAt" | "updatedAt">): PromptTemplate {
  return {
    ...template,
    builtin: true,
    version: 1,
    createdAt: NOW,
    updatedAt: NOW,
  };
}

export const BUILTIN_PROMPT_TEMPLATES: PromptTemplate[] = [
  createBuiltinTemplate({
    id: "builtin-paper-summary",
    title: "论文摘要",
    description: "快速整理当前材料的研究目标、方法、结果和结论。",
    category: "reading",
    systemPrompt: "You are a scientific research copilot. Answer concisely and evidence-first.",
    userPrompt: [
      "请基于以下内容生成论文摘要。",
      "",
      "# 当前文件",
      "{{current_file}}",
      "",
      "# 当前文件内容",
      "{{current_file_content}}",
      "",
      "输出要求：",
      "1. Conclusion",
      "2. Evidence",
      "3. Next Actions",
    ].join("\n"),
    surfaces: ["chat", "selection", "evidence"],
    outputMode: "structured-chat",
    requiredContext: ["current_file_content"],
    optionalContext: ["current_file"],
    pinned: true,
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-method-breakdown",
    title: "方法拆解",
    description: "把方法流程拆成输入、步骤、假设和风险。",
    category: "reading",
    systemPrompt: "You are an evidence-first research analyst.",
    userPrompt: [
      "请拆解当前研究材料的方法设计。",
      "",
      "# 当前选区",
      "{{selected_text}}",
      "",
      "# 当前文件内容",
      "{{current_file_content}}",
      "",
      "输出要求：",
      "1. Method Outline",
      "2. Evidence",
      "3. Risks / Open Questions",
    ].join("\n"),
    surfaces: ["chat", "selection"],
    outputMode: "structured-chat",
    requiredContext: ["selected_text"],
    optionalContext: ["current_file_content"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-innovation-points",
    title: "创新点提炼",
    description: "提炼材料中的创新点、边界和适用条件。",
    category: "reading",
    systemPrompt: "You are a scientific research copilot. Surface novelty precisely and avoid hype.",
    userPrompt: [
      "请提炼当前材料的创新点。",
      "",
      "# 当前文件内容",
      "{{current_file_content}}",
      "",
      "输出要求：",
      "1. Novelty",
      "2. Supporting Evidence",
      "3. Applicability / Limits",
    ].join("\n"),
    surfaces: ["chat", "selection"],
    outputMode: "structured-chat",
    requiredContext: ["current_file_content"],
    optionalContext: ["selected_text"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-annotation-reading-note",
    title: "基于批注生成阅读笔记",
    description: "把 PDF 批注整理成研究阅读笔记。",
    category: "annotation",
    systemPrompt: "You are a scientific note organizer. Convert annotation evidence into durable notes.",
    userPrompt: [
      "请基于当前 PDF 批注整理阅读笔记。",
      "",
      "# PDF 批注",
      "{{pdf_annotations}}",
      "",
      "# 当前文件",
      "{{current_file}}",
      "",
      "输出要求：",
      "1. Reading Note",
      "2. Evidence",
      "3. Follow-up Questions",
    ].join("\n"),
    surfaces: ["chat", "selection", "evidence"],
    outputMode: "draft",
    requiredContext: ["pdf_annotations"],
    optionalContext: ["current_file"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-compress-summary",
    title: "压缩成摘要",
    description: "将当前内容压缩为更短的摘要。",
    category: "writing",
    systemPrompt: "You are an academic writing assistant. Compress content without losing meaning.",
    userPrompt: [
      "请将以下内容压缩为一段摘要。",
      "",
      "{{selected_text}}",
      "",
      "如当前没有选区，则使用当前文件内容。",
      "{{current_file_content}}",
    ].join("\n"),
    surfaces: ["chat", "selection", "workbench"],
    outputMode: "chat",
    requiredContext: [],
    optionalContext: ["selected_text", "current_file_content"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-expand-section",
    title: "扩写成节",
    description: "将摘要或提纲扩写成结构化章节。",
    category: "writing",
    systemPrompt: "You are an academic writing assistant. Expand notes into coherent sections.",
    userPrompt: [
      "请将以下内容扩写成结构化章节。",
      "",
      "# 当前选区",
      "{{selected_text}}",
      "",
      "# 当前草稿",
      "{{active_draft}}",
    ].join("\n"),
    surfaces: ["chat", "selection", "workbench"],
    outputMode: "draft",
    requiredContext: [],
    optionalContext: ["selected_text", "active_draft"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-academic-tone",
    title: "转学术语气",
    description: "把现有内容改写成更克制的学术表达。",
    category: "writing",
    systemPrompt: "You are an academic writing editor. Preserve meaning, improve scholarly tone.",
    userPrompt: [
      "请将以下内容改写为更正式的学术语气。",
      "",
      "{{selected_text}}",
      "",
      "{{current_file_content}}",
    ].join("\n"),
    surfaces: ["chat", "selection", "workbench"],
    outputMode: "chat",
    requiredContext: [],
    optionalContext: ["selected_text", "current_file_content"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-export-polish",
    title: "导出前润色检查",
    description: "在导出前检查结构、语气和明显问题。",
    category: "export",
    systemPrompt: "You are a publication-oriented editor. Review structure, clarity, and missing elements.",
    userPrompt: [
      "请对以下内容做导出前润色检查。",
      "",
      "{{current_file_content}}",
      "",
      "输出要求：",
      "1. Key Issues",
      "2. Suggested Fixes",
      "3. Ready / Not Ready",
    ].join("\n"),
    surfaces: ["chat", "workbench"],
    outputMode: "structured-chat",
    requiredContext: ["current_file_content"],
    optionalContext: ["current_file"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-compare-evidence",
    title: "比较两组 evidence",
    description: "围绕证据集合进行比较分析。",
    category: "comparison",
    systemPrompt: "You are an evidence comparison assistant. Highlight similarities, differences, and confidence.",
    userPrompt: [
      "请比较以下证据集合。",
      "",
      "{{selected_evidence}}",
      "",
      "输出要求：",
      "1. Common Ground",
      "2. Differences",
      "3. Decision Impact",
    ].join("\n"),
    surfaces: ["chat", "evidence"],
    outputMode: "structured-chat",
    requiredContext: ["selected_evidence"],
    optionalContext: ["current_file"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-compare-pdf-items",
    title: "比较两个 PDF 条目",
    description: "比较不同 PDF 材料在方法和结论上的差异。",
    category: "comparison",
    systemPrompt: "You are a research comparison assistant.",
    userPrompt: [
      "请比较以下研究材料。",
      "",
      "# 证据",
      "{{selected_evidence}}",
      "",
      "# 批注",
      "{{pdf_annotations}}",
    ].join("\n"),
    surfaces: ["chat", "evidence"],
    outputMode: "structured-chat",
    requiredContext: ["selected_evidence"],
    optionalContext: ["pdf_annotations"],
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-generate-proposal",
    title: "生成 proposal",
    description: "把当前内容转成可审阅的工作计划。",
    category: "planning",
    systemPrompt: "You are a safe workflow planner. Produce reviewable, approval-gated plans only.",
    userPrompt: [
      "请为以下内容生成一个可审阅的工作计划。",
      "",
      "{{selected_text}}",
      "",
      "{{current_file_content}}",
    ].join("\n"),
    surfaces: ["chat", "selection", "evidence", "workbench"],
    outputMode: "proposal",
    requiredContext: [],
    optionalContext: ["selected_text", "current_file_content"],
    pinned: true,
    preferredProvider: null,
    preferredModel: null,
  }),
  createBuiltinTemplate({
    id: "builtin-generate-target-drafts",
    title: "生成 target draft set",
    description: "将当前计划或证据整理成目标草稿集合。",
    category: "planning",
    systemPrompt: "You are a workflow assistant. Prepare target drafts for user review.",
    userPrompt: [
      "请将以下内容整理成目标草稿集合。",
      "",
      "{{selected_evidence}}",
      "",
      "{{active_proposal}}",
    ].join("\n"),
    surfaces: ["chat", "evidence", "workbench"],
    outputMode: "target-draft-set",
    requiredContext: [],
    optionalContext: ["selected_evidence", "active_proposal"],
    preferredProvider: null,
    preferredModel: null,
  }),
];
